apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- backend-secret.yaml
- backend-deployment.yaml
- backend-service.yaml
- mongo-headless-service.yaml
- mongo-statefulset.yaml
images:
- name: m4k-pipeline
  newTag: local-v2
patches:
- path: patches/configmap-version.yaml
  target:
    kind: ConfigMap
    name: first-pipeline-config
    namespace: boiler-room
